### ISSUE TITLE
Trim down image size by removing extraneous non-minimal cruft

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-centos-8#2]
After completing Issue #1, I noticed the image size is just over 1 GB. If possible, I'd like to get it more in the 600-800 MB range, max. Maybe there really are 200 MB more things in CentOS 8 that are unavoidable, but I doubt it.

There might be more firmwares I don't need (I remember seeing the installer installing them along with 700+ other packages), or other things that are only necessary for a GUI install that are still getting installed off the 7 GB DVD iso.

**Comment by ronjarrell** [comment]
Try installing @^minimal-environment

It installs just core, and has options to enable guest-agents, and standard with --optional.

They're defined in 8/BaseOS/x86_64/kickstart/repodata/*-coms-BaseOS.x86_64.xml

My system image went from fitting in a 2G virtual disk to needing 3G.

**Comment by caffeinejolt** [comment]
Possibly useful: https://github.com/uboreas/centos-8-minimal

**Comment by geerlingguy** [comment]
Closing as all development work for my packer boxes is moving into a central repository, see: https://github.com/geerlingguy/packer-boxes/issues/45
