### ISSUE TITLE
Switch to boot.iso by fixing issue with mirrors not being reachable

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/packer-centos-8#3]
After completing issue #1, I had switched the install to use the DVD ISO instead of the boot.iso. I was having trouble with the boot.iso, namely I couldn't get it to either automatically choose a mirror, or accept any mirror manually entered (either via kickstart, via CLI directly, or via the GUI installer directly). I verified the VM had an active and working network connection (it showed as so in the installer, and in CLI I could ping google so DNS and TCP were happy).

I would like to use the boot.iso and do a network install instead of the dvd.iso since it's about 8x smaller and it's easier to download-while-installing since I don't need all 7+ GB of packages that are available in the DVD image.

**Comment by ronjarrell** [comment]
I'm having no trouble with using boot+url.  I actually boot with an iso_url from my local repo copy, and the in the ks file I have a

url --url=http://myhost/centos/8/BaseOS/x86_64/os

**Comment by TimRots** [comment]
PR #5 shows a working example using the CentOS-8-x86_64-1905-boot.iso

observational note: defining disk_size < 81920 in the packer json will cause anaconda to segfault during the install.

**Comment by lrk** [comment]
@geerlingguy 
There is a known config bug (https://bugs.centos.org/view.php?id=16456 don't really understand the full details) but you have to use thoses repositories url:

- http://mirror.centos.org/centos/8/BaseOS/x86_64/kickstart 
- http://mirror.centos.org/centos/8/AppStream/x86_64/kickstart/

see: https://community.theforeman.org/t/cant-kickstart-centos-8/15566/3

i'm currently using https://access.redhat.com/labs/kickstartconfig/ to do some tests, but right now, it seem to pass the previous problem configuring repositories, and start to download packages

**Comment by geerlingguy** [comment]
Closing as all development work for my packer boxes is moving into a central repository, see: https://github.com/geerlingguy/packer-boxes/issues/45
