### ISSUE TITLE
Role not found

### ISSUE THREAD

**Issue by Sprbb** [geerlingguy/packer-centos-8#8]
When I executed:

packer build -var 'version=1.2.0' centos8.json

This happend:

    virtualbox-iso: - downloading role 'packer-rhel', owned by geerlingguy
==> virtualbox-iso: [WARNING]: - geerlingguy.packer-rhel was NOT installed successfully: - sorry,
==> virtualbox-iso: geerlingguy.packer-rhel was not found on https://galaxy.ansible.com/api/.
==> virtualbox-iso: ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
==> virtualbox-iso: Provisioning step had errors: Running the cleanup provisioner, if present...
==> virtualbox-iso: Deregistering and deleting VM...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error executing Ansible: Error executing Ansible Galaxy: Non-zero exit status: 1

**Comment by geerlingguy** [comment]
Closing as all development work for my packer boxes is moving into a central repository, see: https://github.com/geerlingguy/packer-boxes/issues/45

(Also this has been fixed in that repository.)
